"""
Django settings for PIcommit project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

current_dir = os.path.dirname(os.path.abspath(__file__))

base_dir = os.path.dirname(current_dir)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-y^b0))-h+$x*%_#!bu*_c(p^+b-3-7u^$l6!s(xt^&y^)-c8*o'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'whereToGo.apps.whereToGoConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'PIcommit.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'PIcommit.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
MEDIA_ROOT = os.path.join(base_dir, 'images')
MEDIA_URL = '/images/'
apikey = "q0tSC7AcYE6xAAKLYhw9cVZWqANwLuno"
api_secret = "V50srWiDG7m5Vr3d"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
aeropuertos = {
    "Madrid": "-3.5673,40.4919",
    "Coruña": "-8.3773,43.3028",
    "Santiago de Compostela": "-8.4157,42.8978",
    "Barcelona": "2.13684, 41.3520",
    "Málaga": "-4.4994,36.6749",
    "Alicante": "-0.532,38.2822",
    "Bilbao": "-2.9256,43.3014",
    "Ibiza": "1.3632,38.8729",
    "Reus": "1.1669,41.1474",
    "Zaragoza": "-0.8898,41.6561",
    "Vigo-Peinador": "-8.6323,42.2243",
    "Salamanca": "-5.6617,40.965",
    "Logroño-Agoncillo": "-2.3181,42.4547",
    "León": "-5.6428,42.589",
    "Badajoz": "-6.8211,38.8914",
    "Asturias": "-6.0324,43.5635",
    "Huesca-Pirineos": "-0.3257,42.0761",
    "Vitoria": "-2.7228,42.8828",
    "San Sebastián": "-1.7906,43.3568",
    "Sabadell": "2.1058,41.5183",

}
aeropuertos_iata = {
    "Madrid": "MAD",
    "Coruña": "LCG",
    "Santiago de Compostela": "SCQ",
    "Barcelona": "BCN",
    "Málaga": "AGP",
    "Alicante": "ALC",
    "Bilbao": "BIO",
    "Ibiza": "IBZ",
    "Reus": "REU",
    "Zaragoza": "ZAZ",
    "Vigo-Peinador": "VGO",
    "Salamanca": "SLM",
    "Logroño-Agoncillo": "RJL",
    "León": "LEN",
    "Badajoz": "BJZ",
    "Asturias": "OVD",
    "Huesca-Pirineos": "HSK",
    "Vitoria": "VIT",
    "San Sebastián": "EAS",
    "Sabadell": "QSA",
    
}
aeropuertos_iata_coor= {
    "MAD": "-3.5673,40.4919",
    "LCG": "-8.3773,43.3028",
    "SCQ": "-8.4157,42.8978",
    "BCN": "2.13684, 41.3520",
    "AGP": "-4.4994,36.6749",
    "ALC": "-0.532,38.2822",
    "BIO": "-2.9256,43.3014",
    "IBZ": "1.3632,38.8729",
    "REU": "1.1669,41.1474",
    "ZAZ": "-0.8898,41.6561",
    "VGO": "-8.6323,42.2243",
    "SLM": "-5.6617,40.965",
    "RJL": "-2.3181,42.4547",
    "LEN": "-5.6428,42.589",
    "BJZ": "-6.8211,38.8914",
    "OVD": "-6.0324,43.5635",
    "HSK": "-0.3257,42.0761",
    "VIT": "-2.7228,42.8828",
    "EAS": "-1.7906,43.3568",
    "QSA": "2.1058,41.5183",
}
lugares = [
            {"nombre": "Madrid", "lat": 40.4919, "lon": -3.5673},
            {"nombre": "La Coruña", "lat": 43.3028, "lon": -8.3773},
            {"nombre": "Santiago de Compostela", "lat": 42.8978, "lon": -8.4157},
            {"nombre": "Barcelona", "lat": 41.1474, "lon": 1.1669},
            {"nombre": "Málaga", "lat": 36.6749, "lon": -4.4994},
            {"nombre": "Alicante", "lat": 38.2822, "lon": -0.532},
            {"nombre": "Bilbao", "lat": 43.3014, "lon": -2.9256},
            {"nombre": "Ibiza", "lat": 38.8729, "lon": 1.3632},
            {"nombre": "Reus", "lat": 41.1474, "lon": 1.1669},
            {"nombre": "Zaragoza", "lat": 41.6561, "lon": -0.8898},
            {"nombre": "Vigo", "lat": 42.2328, "lon": -8.7226},
            {"nombre": "Salamanca", "lat": 40.965, "lon": -5.6617},
            {"nombre": "Logroño", "lat": 42.4547, "lon": -2.3181},
            {"nombre": "León", "lat": 42.589, "lon": -5.6428},
            {"nombre": "Badajoz", "lat": 38.8914, "lon": -6.8211},
            {"nombre": "Asturias", "lat": 43.5635, "lon": -6.0324},
            {"nombre": "Huesca", "lat": 42.0761, "lon": -0.3257},
            {"nombre": "Vitoria", "lat": 42.8828, "lon": -2.7228},
            {"nombre": "San Sebastián", "lat": 43.3568, "lon": -5.9},
            {"nombre": "Sabadell", "lat": 41.5183, "lon": 2.1058},
        ]